In [4]:
import pandas as pd
from pathlib import Path
import altair as alt

data = pd.read_csv("website/cleaned_listings.csv")

data.head()

print(data.isnull().sum())
data.head()

price                             0
number_of_reviews                 0
latitude                          0
longitude                         0
room_type                         0
minimum_nights                    0
availability_365                  0
review_scores_rating              0
license                           0
neighbourhood_cleansed            0
calculated_host_listings_count    0
bedrooms                          0
name                              0
number_of_reviews_ltm             0
host_is_superhost                 0
estimated_occupancy_l365d         0
estimated_revenue_l365d           0
has_license                       0
dtype: int64

,price,number_of_reviews,latitude,longitude,room_type,minimum_nights,availability_365,review_scores_rating,license,neighbourhood_cleansed,calculated_host_listings_count,bedrooms,name,number_of_reviews_ltm,host_is_superhost,estimated_occupancy_l365d,estimated_revenue_l365d,has_license
0,125.0,26,42.36413,-71.02991,Entire home/apt,29,262,4.96,none,East Boston,1,1.0,HARBORSIDE-Walk to subway,1,t,58,7250.0,0
1,142.0,137,42.32844,-71.09581,Entire home/apt,3,103,4.82,STR-490093,Roxbury,11,1.0,** Fort Hill Inn Private! Minutes to center!**,13,t,78,11076.0,1
2,171.0,139,42.32802,-71.09387,Entire home/apt,3,93,4.81,STR-491702,Roxbury,11,0.0,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex",11,t,66,11286.0,1
3,140.0,29,42.35867,-71.06307,Entire home/apt,91,210,4.69,none,Beacon Hill,8,1.0,Curved Glass Studio/1bd facing Park,0,t,0,0.0,0
4,152.0,9,42.35173,-71.08685,Entire home/apt,91,217,4.33,none,Back Bay,12,0.0,Bostons Best Rentals -Studio Prestigious Back Bay,0,t,0,0.0,0

In [5]:
import geopandas as gpd

filepath = "neighbourhoods.geojson"
neigh = gpd.read_file(filepath)
neigh_small = neigh[["neighbourhood", "geometry"]]

gdf_list = gpd.GeoDataFrame(
    data,
    geometry=gpd.points_from_xy(data.longitude, data.latitude),
    crs="EPSG:4326"
)

joined = gpd.sjoin(gdf_list, neigh_small, how="left", predicate="within")

joined.head()

,price,number_of_reviews,latitude,longitude,room_type,minimum_nights,availability_365,review_scores_rating,license,neighbourhood_cleansed,...,bedrooms,name,number_of_reviews_ltm,host_is_superhost,estimated_occupancy_l365d,estimated_revenue_l365d,has_license,geometry,index_right,neighbourhood
0,125.0,26,42.36413,-71.02991,Entire home/apt,29,262,4.96,none,East Boston,...,1.0,HARBORSIDE-Walk to subway,1,t,58,7250.0,0,POINT (-71.02991 42.36413),11,East Boston
1,142.0,137,42.32844,-71.09581,Entire home/apt,3,103,4.82,STR-490093,Roxbury,...,1.0,** Fort Hill Inn Private! Minutes to center!**,13,t,78,11076.0,1,POINT (-71.09581 42.32844),8,Roxbury
2,171.0,139,42.32802,-71.09387,Entire home/apt,3,93,4.81,STR-491702,Roxbury,...,0.0,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex",11,t,66,11286.0,1,POINT (-71.09387 42.32802),8,Roxbury
3,140.0,29,42.35867,-71.06307,Entire home/apt,91,210,4.69,none,Beacon Hill,...,1.0,Curved Glass Studio/1bd facing Park,0,t,0,0.0,0,POINT (-71.06307 42.35867),14,Beacon Hill
4,152.0,9,42.35173,-71.08685,Entire home/apt,91,217,4.33,none,Back Bay,...,0.0,Bostons Best Rentals -Studio Prestigious Back Bay,0,t,0,0.0,0,POINT (-71.08685 42.35173),10,Back Bay

In [6]:
input_dropdown = alt.binding_select(options = [None, 'Roslindale', 'Jamaica Plain', 'Mission Hill',
       'Longwood Medical Area', 'Bay Village', 'Leather District',
       'Chinatown', 'North End', 'Roxbury', 'South End', 'Back Bay',
       'East Boston', 'Charlestown', 'West End', 'Beacon Hill',
       'Downtown', 'Fenway', 'Brighton', 'West Roxbury', 'Hyde Park',
       'Mattapan', 'Dorchester', 'South Boston Waterfront',
       'South Boston', 'Allston', 'Harbor Islands'],
                                    labels = ['All','Roslindale', 'Jamaica Plain', 'Mission Hill',
       'Longwood Medical Area', 'Bay Village', 'Leather District',
       'Chinatown', 'North End', 'Roxbury', 'South End', 'Back Bay',
       'East Boston', 'Charlestown', 'West End', 'Beacon Hill',
       'Downtown', 'Fenway', 'Brighton', 'West Roxbury', 'Hyde Park',
       'Mattapan', 'Dorchester', 'South Boston Waterfront',
       'South Boston', 'Allston', 'Harbor Islands'],
                                     name = "Neighbor: " )

selection = alt.selection_point(fields = ['neighbourhood'], bind = input_dropdown)

alt.Chart(joined).mark_bar().transform_filter(selection).encode(
    x = alt.X('has_license:N'),
    y = alt.Y('count(has_license):Q'),
).add_params(
    selection
)

alt.Chart(...)

In [7]:
input_dropdown = alt.binding_select(
    options=[None, 'Roslindale', 'Jamaica Plain', 'Mission Hill',
             'Longwood Medical Area', 'Bay Village', 'Leather District',
             'Chinatown', 'North End', 'Roxbury', 'South End', 'Back Bay',
             'East Boston', 'Charlestown', 'West End', 'Beacon Hill',
             'Downtown', 'Fenway', 'Brighton', 'West Roxbury', 'Hyde Park',
             'Mattapan', 'Dorchester', 'South Boston Waterfront',
             'South Boston', 'Allston', 'Harbor Islands'],
    labels=['All','Roslindale', 'Jamaica Plain', 'Mission Hill',
            'Longwood Medical Area', 'Bay Village', 'Leather District',
            'Chinatown', 'North End', 'Roxbury', 'South End', 'Back Bay',
            'East Boston', 'Charlestown', 'West End', 'Beacon Hill',
            'Downtown', 'Fenway', 'Brighton', 'West Roxbury', 'Hyde Park',
            'Mattapan', 'Dorchester', 'South Boston Waterfront',
            'South Boston', 'Allston', 'Harbor Islands'],
    name="Neighbor: "
)

selection = alt.selection_point(fields=['neighbourhood'], bind=input_dropdown)

base = (
    alt.Chart(joined)
    .add_params(selection)
    .transform_filter(selection)
)

joined['price'] = pd.to_numeric(joined['price'], errors='coerce')

count_bar = base.mark_bar().encode(
    x=alt.X('has_license:N', title='Has License'),
    y=alt.Y('count():Q', title='Count of Listings'),
    color='has_license:N',
    tooltip=['has_license:N', 'count():Q']
).properties(title='Licensed vs Unlicensed (Count)',
             height = 600, width = 400)


price_bar = base.mark_bar().encode(
    x=alt.X('has_license:N', title='Has License'),
    y=alt.Y('mean(price):Q', title='Average Price'),
    color='has_license:N',
    tooltip=['has_license:N', 'mean(price):Q']
).properties(title='Licensed vs Unlicensed (Average Price)', height = 600, width = 400)

final_chart = count_bar | price_bar

c_json = final_chart.to_json()

with open('website/t5-barplot1_spec.json', 'w') as f:
    f.write(c_json)